inputs:
  COMPANY:
    type: string
    required: true
  branch_name: 
    type: string
    required: true

runs:
  using: "composite"
  steps:
    # - name: Debug Inputs
    #   shell: bash
    #   run: |
    #     echo ${{ branch_name }}
    #     echo ${{ inputs.COMPANY }}

    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch-name}}
          
    - name: "check"
      shell: powershell
      run: |
          Write-Host "Branch name: ${{ inputs.branch_name }}"
          if ("${{ inputs.branch_name }}" -eq "main") {
            $repository = "release"
          } else {
            $repository = "done"
          }
