inputs:
  COMPANY:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Debug Inputs
      shell: bash
      run: |
        echo "COMPANY is: '${COMPANY}'"
      env:
        COMPANY: ${{ inputs.COMPANY }}
