inputs:
  COMPANY:
    type: string
    required: true
  branch_name: 
    type: string
    required: true

runs:
  using: "composite"
  steps:
    # - name: Debug Inputs
    #   shell: bash
    #   run: |
    #     echo ${{ branch_name }}
    #     echo ${{ inputs.COMPANY }}

    - name: "check"
      shell: powershell
      run: |
          Write-Host "Branch name: ${{ github.ref }}"
          if ("${{ github.ref }}" -eq "main") {
            $repository = "release"
          } else {
            $repository = "done"
          }
