name : Secrets Passthrough

on: 
  worflow_call:
    inputs:
      branch_name: 
        type: string
        required: true
      environment: 
        type: string
        required: true

jobs:

  execution_steps:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      
      - name: test-secret
        uses: maheshaila01/env_secrets/.githubactions/secrets-test.yml@main
        secrets: inherit