name : Secrets Passthrough

on: 
  workflow_call:
    inputs:
      branch_name: 
        type: string
        required: true
      environment: 
        type: string
        required: true

jobs:

  execution_steps:
    runs-on: windows-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch-name}}
      
      - name: test-secret
        uses: maheshaila01/env_secrets/.github/actions/secrets-test@main
        with:
          COMPANY: ${{VARS.COMPANY }}
          branch_name: ${{inputs.branch_name}}
