name : Secrets Passthrough

on: 
  workflow_call:
    inputs:
      branch-name: 
        type: string
        required: true
      environment: 
        type: string
        required: true

jobs:

  execution_steps:
    runs-on: windows-latest
    environment: ${{ inputs.environment }}
    steps:
    
      - name: 🚀 Push Docker Image To Jfrog
        id: build-and-push-docker-image
        run: |
            $branchName = '${{ inputs.branch-name }}'
            if ($branchName -eq 'main' -or $branchName.Contains('Release')) {
              $repository = "release"
            } else {
              $repository = "${{ inputs.environment }}"
            }
             Write-Output $repository
        shell: powershell
